### PR TITLE
WP-33 : Move insert_childs shortcode

### PR DESCRIPTION
**Pull request by c-meier**
The plugin [shortcode-ui](https://fr.wordpress.org/plugins/shortcode-ui/) should be installed to make availablea  shortcode insertion modal in the ui.

### CODE REVIEW

**Comment by ecino** [comment]
Is the plugin mandatory? Was this discussed with Olivier?

**Comment by numerosept** [comment]
yes it was the plugin created by Samuel to put children everywhere on the website
––––––––––––––––––––––––––––––––––––––

Olivier Requet
Département Communication
Compassion Suisse

Rue Galilée 3, 1400 Yverdon-les-Bains
Tel: +41 24 434 21 25 Mob: +41 78 895 89 60

www.compassion.ch<http://www.compassion.ch> – orequet@compassion.ch<mailto:orequet@compassion.ch>


[cid:8BC09CEA-6C2D-4EBA-A52D-60FB704C8371@compassion.ch] <https://compassion.ch/ecrire/>
<https://compassion.ch/ecrire/>

Le 1 avr. 2019 à 09:33, ecino <notifications@github.com<mailto:notifications@github.com>> a écrit :


Is the plugin mandatory? Was this discussed with Olivier?

**Comment by c-meier** [comment]
Yes it was discussed with Oliver. No `shortcode-ui` isn't mandatory, but it makes the insertion of shortcode easier. It can also be used as a documentation of the available plugin

**Comment by ecino** [comment]
I installed the plugin `shortcode-ui` on devcomp.site. Olivier can decide if he wants it on the production website. (I let you install it). @numerosept please can you test that everything works on devcomp and tell me when it's ready to be merged in production ?

**Pull request merged**
